[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
slider_pvp = "9EeZ1eFrs8QAop7c6ihE4CiXenjVpGPdmFyv6w3XnmcT"

[programs.devnet]
slider_pvp = "9EeZ1eFrs8QAop7c6ihE4CiXenjVpGPdmFyv6w3XnmcT"

[programs.mainnet]
slider_pvp = "9EeZ1eFrs8QAop7c6ihE4CiXenjVpGPdmFyv6w3XnmcT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

